[from-external]
exten => _X.,1,NoOp(Incoming call to AI Extension: ${EXTEN})
 same => n,Stasis(dograh)
 same => n,Hangup()

[default]
exten => _+X.,1,NoOp(Outbound call from Dograh to raw extension with plus: ${EXTEN})
 same => n,Set(CALLERID(num)=YOUR_VOBIZ_CALLERID_NUM)
 same => n,Set(CALLERID(name)=YOUR_VOBIZ_CALLERID_NAME)
 same => n,Set(CLEAN_NUMBER=${FILTER(0123456789+,${EXTEN})})
 same => n,NoOp(Cleaned number to dial: ${CLEAN_NUMBER})
 same => n,Dial(PJSIP/vobiz-trunk/sip:${CLEAN_NUMBER}@YOUR_VOBIZ_DOMAIN)
 same => n,Hangup()

exten => _X.,1,NoOp(Outbound call from Dograh to raw extension: ${EXTEN})
 same => n,Set(CALLERID(num)=YOUR_VOBIZ_CALLERID_NUM)
 same => n,Set(CALLERID(name)=YOUR_VOBIZ_CALLERID_NAME)
 same => n,Set(CLEAN_NUMBER=${FILTER(0123456789+,${EXTEN})})
 same => n,NoOp(Cleaned number to dial: ${CLEAN_NUMBER})
 same => n,Dial(PJSIP/vobiz-trunk/sip:${CLEAN_NUMBER}@YOUR_VOBIZ_DOMAIN)
 same => n,Hangup()
